### PR TITLE
[RDY] Overhaul build config for Eclipse plugin

### PR DESCRIPTION
**Pull request by Hjdskes**

### CODE REVIEW

**Comment by Hjdskes** [comment]
Commit 5883a64aee0488b795c857c41c037ff0a119173c significantly changed our build configuration in that we now inherit from Spoofax's build config. This means that when you checkout this branch, you will have to do some manual labor (ugh!) to get things into a workable state:
1. Clone [spoofax-releng](https://github.com/metaborg/spoofax-releng) into your Eclipse workspace directory:  
   
   ``` bash
   cd $ECLIPSE_WORKSPACE
   git clone git@github.com:metaborg/spoofax-releng.git
   ```
2. Move all contents from the `spoofax-releng` folder just created into your workspace directory (or alternatively move your `spoofax-shell` folder inside the `spoofax-releng` folder):  
   
   ``` bash
   mv spoofax-releng/{.*,*} .
   rmdir spoofax-releng
   ```
   
   or:
   
   ``` bash
   mv spoofax-shell spoofax-releng/
   ```
3. Run to following commands to initialise and update the git submodules:  
   
   ``` bash
   git submodule init
   git submodule update
   ```
   
   This will clone all projects into your workspace directory, which can take a while. Alternatively, I believe we can get away with only cloning [spoofax-deploy](https://github.com/metaborg/spoofax-deploy) into a directory named `releng`, but I have not confirmed this. Another trick to increase the update speed is to use the `--depth x` parameter to clone only the `x` last commits of every repository.

I saved our parent pom (which is now just an aggregation pom) such that the core and console modules can be build from our project's root directory (e.g. spoofax-shell). Due to an issue with Tycho the Eclipse plugin will always have to be build standalone (~~for which we need to look at TravisCI as well~~), so, to build our modules:

``` bash
cd spoofax-shell
mvn clean install # this will build (and install, see below) the core and console modules, in that order
cd org.metaborg.spoofax.shell.eclipse
mvn clean verify # this will build the Eclipse module. The installed core module can now be resolved as a dependency.
```

## 

~~Eventually I will squash the first three commits, but not until I am certain that this actually resolves our issues. For now, it seems to have resolved the unresolved dependency issue we ran into with our core module's OSGi bundle. We do however still get the ArrayStoreException, which I now believe is caused by us using Java 8 versus Spoofax using Java 7. I will port our code to Java 7 after having resolved the Hamcrest dependency issue currently appearing in the console module~~.

~~The static analysis config that is already present in the core and console modules' pom files still needs to be copy pasted (😢) into the Eclipse module's pom file, but I first want to get everything in a working state~~. Perhaps after this we can figure out a way to have this in one place again, but right now this is the least of our problems.

Lastly: I have no idea how this influences our site build... 😕

**Comment by Hjdskes** [comment]
The Hamcrest dependency issue is resolved in 9593c0d8f1480252defbb78f8798af1b03158126. I will now start on fixing the Eclipse module's build.

**Comment by Hjdskes** [comment]
Eclipse build is working as of ddf665a48767fea1b654578e8f507838c01dd0b0.

**Comment by Hjdskes** [comment]
TravisCI's config is updated to build the Eclipse module in 81fb56c48faed16fbd23ea3c107ee24e5d719956.

Please discuss on whether or not we should keep our reactor build, as currently the Eclipse plugin already needs to be build separately I don't think it's much of an advantage. (Especially under the assumption that eventually manual testing will move to the Eclipse plugin instead of the console client).

**Comment by Unia** [comment]
Please discuss on whether or not we should keep our reactor build, as currently the Eclipse plugin already needs to be build separately I don't think it's much of an advantage. (Especially under the assumption that eventually manual testing will move to the Eclipse plugin instead of the console client).

**Comment by Balletie** [comment]
This problem is most probably due to different classloaders. We should register Guice and other dependencies as "Buddies" for our eclipse plugin. Then when Guice cannot find our class, the class is looked up in the classes of our bundle (the eclipse plugin). See http://rajakannappan.blogspot.nl/2010/03/eclipse-classloading-and-buddy-policy.html

**Comment by Hjdskes** [comment]
The remaining issues have been resolved. The site build is currently broken in that it does not properly link between the aggregator and the modules, but it is right now more important to continue development than it is to fix the site. I'll open an issue for this later so that we can fix the site in due time.

**Comment by Hjdskes** [comment]
I have removed the Eclipse-specific code from this PR such that this one can be merged after #17. I'm working on a new branch to get a basic plugin going at the moment.

@Balletie @gfokkema Please review.

**Pull request merged**
